openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://aes-demo.com
    description: Main application - Aircraft Bazaar. Demonstration only.
  # - url: http://staging-api.example.com
    # description: Optional server description, e.g. Internal staging server for testing
paths:
  /:
    get:
      summary: Returns main page of application.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string